addpath(genpath('U:/github/texa/'));
%drawSamples('C:/OPT_dataset', 'C:/OPT_dataset/Description', 'E:/surs', 11, 31, 100);
%drawSamples('C:/OPT_dataset', 'C:/OPT_dataset/Description', 'E:/surs', 21, 31, 100);
%drawSamples('C:/OPT_dataset', 'C:/OPT_dataset/Description', 'E:/surs', 31, 31, 100);
%drawSamples('C:/OPT_dataset', 'C:/OPT_dataset/Description', 'E:/surs', 41, 31, 100);
%drawSamples('C:/OPT_dataset', 'C:/OPT_dataset/Description', 'E:/surs', 51, 31, 100);
%drawSamples('C:/OPT_dataset', 'C:/OPT_dataset/Description', 'E:/surs', 61, 31, 100);
%drawSamples('C:/OPT_dataset', 'C:/OPT_dataset/Description', 'E:/surs', 71, 31, 100);
drawSamples('C:/OPT_dataset', 'C:/OPT_dataset/Description', 'F:/surs', 81, 31, 100);
%drawSamples('C:/OPT_dataset', 'C:/OPT_dataset/Description', 'F:/surs', 91, 31, 100);
%drawSamples('C:/OPT_dataset', 'C:/OPT_dataset/Description', 'F:/surs', 101,31, 100);
%drawSamples('C:/OPT_dataset', 'C:/OPT_dataset/Description', 'F:/surs', 111,31, 100);
