addpath(genpath('U:/github/texa/'));
drawSamples('C:/OPT_dataset', 'C:/OPT_dataset/Description', 'E:/surs', 11, 21, 200);
drawSamples('C:/OPT_dataset', 'C:/OPT_dataset/Description', 'E:/surs', 41, 21, 200);
drawSamples('C:/OPT_dataset', 'C:/OPT_dataset/Description', 'E:/surs', 31, 21, 200);
drawSamples('C:/OPT_dataset', 'C:/OPT_dataset/Description', 'E:/surs', 51, 21, 200);
drawSamples('C:/OPT_dataset', 'C:/OPT_dataset/Description', 'E:/surs', 61, 21, 200);
drawSamples('C:/OPT_dataset', 'C:/OPT_dataset/Description', 'E:/surs', 71, 21, 200);
drawSamples('C:/OPT_dataset', 'C:/OPT_dataset/Description', 'E:/surs', 81, 21, 200);
drawSamples('C:/OPT_dataset', 'C:/OPT_dataset/Description', 'E:/surs', 91, 21, 200);
drawSamples('C:/OPT_dataset', 'C:/OPT_dataset/Description', 'E:/surs', 101,21, 200);
