addpath(genpath('U:/github/texa/'));
%drawSamples('C:/OPT_dataset', 'C:/OPT_dataset/Description', 'F:', 11, 500);
%drawSamples('C:/OPT_dataset', 'C:/OPT_dataset/Description', 'F:', 41, 500);
%drawSamples('C:/OPT_dataset', 'C:/OPT_dataset/Description', 'F:', 31, 500);
%drawSamples('C:/OPT_dataset', 'C:/OPT_dataset/Description', 'F:', 51, 500);
%drawSamples('C:/OPT_dataset', 'C:/OPT_dataset/Description', 'F:', 61, 500);
drawSamples('C:/OPT_dataset', 'C:/OPT_dataset/Description', 'F:', 71, 500);
drawSamples('C:/OPT_dataset', 'C:/OPT_dataset/Description', 'F:', 81, 500);
drawSamples('C:/OPT_dataset', 'C:/OPT_dataset/Description', 'F:', 91, 500);
drawSamples('C:/OPT_dataset', 'C:/OPT_dataset/Description', 'F:', 101, 500);
